//
// Created by 徐溶延 on 2020/11/8.
//

#ifndef SLIM_MESH_OPTIMIZATION_DATA_SHARED_PATH_H
#define SLIM_MESH_OPTIMIZATION_DATA_SHARED_PATH_H

#ifndef DATA_SHARED_PATH
#define DATA_SHARED_PATH "../data"
#endif

#endif //SLIM_MESH_OPTIMIZATION_DATA_SHARED_PATH_H
